### Sample REST Client for testing requests

### Get all notes
DELETE http://localhost:3001/api/persons/4

### Post a new note
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}