### Sample REST Client for testing requests

### Get all notes
DELETE http://localhost:3001/api/persons/67ef4c7c43ca15941fcd3b35

### Post a new note
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "388-123-4567"
}
### Get all notes
GET http://localhost:3001/api/persons
### Get a note by id
GET http://localhost:3001/api/persons/67ef4c7c43ca15941fcd3b35
